### ISSUE TITLE
Install failing on Nokogiri

### ISSUE THREAD

**Issue by CarlGranstrom** [zendesk/zendesk_apps_tools#219]
Trying to `gem install zendesk_apps_tools` on High Sierra (10.13.1) fails on Nokogiri.

I was able to install the latest version of it when following their installation guide but haven't been able to get the zat installation to work, any ideas?

```Building native extensions.  This could take a while...
ERROR:  Error installing zendesk_apps_tools:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8.1/ext/nokogiri
/usr/local/opt/ruby/bin/ruby -r ./siteconf20171123-40503-12ew816.rb extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.4.2_1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'mini_portile2' (~> 2.1.0) among 8 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/carlgranstrom/.gem/ruby/2.4.0:/usr/local/lib/ruby/gems/2.4.0:/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/gems/2.4.0', execute `gem env` for more information
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:322:in `to_spec'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from extconf.rb:468:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.8.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0/nokogiri-1.6.8.1/gem_make.out```

**Comment by CarlGranstrom** [comment]
Fixed by https://gist.github.com/mcls/3118518
