### ISSUE TITLE
Ruby segfaults

### ISSUE THREAD

**Issue by tonyhb** [zendesk/zendesk_apps_tools#220]
Any time I try and use secrets this happens:

```
/usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194: [BUG] Segmentation fault at 0x00000000000018
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0018 p:---- s:0114 e:000113 CFUNC  :run_machine
c:0017 p:0327 s:0110 e:000109 METHOD /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194
c:0016 p:0063 s:0102 E:0003f8 METHOD /usr/local/bundle/gems/thin-1.7.2/lib/thin/backends/base.rb:73
c:0015 p:0120 s:0097 E:001960 METHOD /usr/local/bundle/gems/thin-1.7.2/lib/thin/server.rb:162
c:0014 p:0186 s:0093 e:000092 METHOD /usr/local/bundle/gems/rack-1.6.8/lib/rack/handler/thin.rb:19
c:0013 p:0013 s:0081 e:000080 METHOD /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1506
c:0012 p:0114 s:0074 e:000073 METHOD /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1444
c:0011 p:0155 s:0065 e:000064 BLOCK  /usr/local/bundle/gems/zendesk_apps_tools-2.8.0/lib/zendesk_apps_tools/command.rb:155 [FINISH]
c:0010 p:---- s:0061 e:000060 CFUNC  :tap
c:0009 p:0066 s:0057 e:000056 METHOD /usr/local/bundle/gems/zendesk_apps_tools-2.8.0/lib/zendesk_apps_tools/command.rb:147
c:0008 p:0078 s:0053 e:000052 METHOD /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27
c:0007 p:0058 s:0045 e:000044 METHOD /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126
c:0006 p:0303 s:0038 e:000037 METHOD /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369
c:0005 p:0068 s:0025 e:000024 METHOD /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444
c:0004 p:0157 s:0018 e:000017 TOP    /usr/local/bundle/gems/zendesk_apps_tools-2.8.0/bin/zat:13 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:0152 s:0008 E:000280 EVAL   /usr/local/bundle/bin/zat:23 [FINISH]
c:0001 p:0000 s:0003 E:0020f0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/local/bundle/bin/zat:23:in `<main>'
/usr/local/bundle/bin/zat:23:in `load'
/usr/local/bundle/gems/zendesk_apps_tools-2.8.0/bin/zat:13:in `<top (required)>'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/zendesk_apps_tools-2.8.0/lib/zendesk_apps_tools/command.rb:147:in `server'
/usr/local/bundle/gems/zendesk_apps_tools-2.8.0/lib/zendesk_apps_tools/command.rb:147:in `tap'
/usr/local/bundle/gems/zendesk_apps_tools-2.8.0/lib/zendesk_apps_tools/command.rb:155:in `block in server'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1444:in `run!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1506:in `start_server'
/usr/local/bundle/gems/rack-1.6.8/lib/rack/handler/thin.rb:19:in `run'
/usr/local/bundle/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
/usr/local/bundle/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
/usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
/usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f2e8bfb84d8 RBP: 0x0000000000000090 RSP: 0x00007ffd909e64a0
 RAX: 0x0000000000000000 RBX: 0x0000000001549b60 RCX: 0x000000000001af13
 RDX: 0x0000000000000000 RDI: 0x00007f2e8c2e4620 RSI: 0x0000000000000000
  R8: 0x0000000000000000  R9: 0x0000000000000000 R10: 0x0000000000000000
 R11: 0x0000000000000293 R12: 0x00007f2e8c2e4620 R13: 0x0000000001549bf0
 R14: 0x0000000000000090 R15: 0x0000000000000090 EFL: 0x0000000000010246

-- C level backtrace information -------------------------------------------
```

**Comment by tonyhb** [comment]
Just an FYI; reporting elsewhere
