### ISSUE TITLE
uninitialized constant ZendeskAppsSupport::Manifest::OverrideError on zat package

### ISSUE THREAD

**Issue by kevinjcoleman** [zendesk/zendesk_apps_tools#230]
I ran `zat package` and the output below was returned. I'm on version `2.8.4`.
```
/Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/validations/manifest.rb:27:in `rescue in call': uninitialized constant ZendeskAppsSupport::Manifest::OverrideError (NameError)
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/validations/manifest.rb:15:in `call'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:32:in `validate'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/zendesk_apps_tools-2.8.4/lib/zendesk_apps_tools/command.rb:74:in `validate'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/zendesk_apps_tools-2.8.4/lib/zendesk_apps_tools/command.rb:104:in `package'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/gems/zendesk_apps_tools-2.8.4/bin/zat:13:in `<top (required)>'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/bin/zat:23:in `load'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/bin/zat:23:in `<main>'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kevincoleman/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kevinjcoleman** [comment]
@ocke @svizzari any ideas?

**Comment by bryan-flynn-zd** [comment]
If your app is an ["app scafoold"](https://github.com/zendesk/app_scaffold) app, make sure you're running `zat package` from the 'dist' directory.

**Comment by kevinjcoleman** [comment]
That worked thanks @bryan-flynn-zd
