### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by chuck-wood** [zendesk/zendesk_apps_tools#231]
I'm running Ruby 2.3 because of #228. This is under Windows 7 (which I'm stuck with as it's my corporate machine). The following commands were run under Git Bash, but I get the same results from the Windows shell. This is a 64-bit machine but I'm using the 32-bit version of everything as I recall seeing somewhere that maybe it's recommended for DevKit or something. It's all kind of running together after so much googling. (I had to fix the Ruby "certificate verify failed" issue first.)

ZAT was working fine until recently -- I think I updated it and this is when the certificate verify issue came up.

```bash
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

$ gem -v
2.7.6

$ zat -v
2.8.4

$ zat validate
D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/app_file.rb:9:in `initialize': Too many open files @ rb_sysopen - D:/dev/download-all-attachments/zendesk/node_modules/nyc/node_modules/cliui/node_modules/wordwrap/README.markdown (Errno::EMFILE)
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/app_file.rb:9:in `new'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/app_file.rb:9:in `initialize'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:81:in `new'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:81:in `block in files'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:77:in `each'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:77:in `files'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:103:in `translation_files'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/validations/manifest.rb:220:in `default_locale_error'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/validations/manifest.rb:40:in `collate_manifest_errors'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/validations/manifest.rb:23:in `call'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.7.0/lib/zendesk_apps_support/package.rb:32:in `validate'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-2.8.4/lib/zendesk_apps_tools/command.rb:74:in `validate'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from D:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-2.8.4/bin/zat:13:in `<top (required)>'
        from D:/Ruby23/bin/zat:23:in `load'
        from D:/Ruby23/bin/zat:23:in `<main>'
```

**Comment by bryan-flynn-zd** [comment]
Hi @chuck-wood -- make sure you are running zat validate (and 'zat package' too) from the directory that contains the final app content. If you're using the app scaffold, that would be the 'dist' directory (IOW, cd to 'dist' and try again).

**Comment by chuck-wood** [comment]
Yeah, I'm in the correct directory. I just noticed that you guys have previous releases saved here. I'll try 2.8.3 and see if it has the same issue.

**Comment by chuck-wood** [comment]
I tried ZAT 2.8.3 and had the same issue. Unfortunately I'm not sure what version of ZAT I was on before upgrading.

**Comment by chuck-wood** [comment]
Turns out it was caused by having a `node_modules` in the project root. (I am not using the scaffold, so there's no `dist` directory. Guess there should be!)

Thanks for the help!
