### ISSUE TITLE
Error installing ZAT on Windows 10 using Ubuntu bash

### ISSUE THREAD

**Issue by darlesson** [zendesk/zendesk_apps_tools#245]
I'm following [Installing and using the Zendesk apps tools](https://develop.zendesk.com/hc/en-us/articles/360001075048) documentation but I'm getting an error when trying to install ZAT.

I have Windows 10 and Ubuntu bash installed. Everything is updated.

These are my steps:

```
$ ruby -v
```

> The documentation says "Ruby is included with Ubuntu for Windows 10". But that wasn't the case. Ruby wasn't installed.

```
$ sudo apt-get install ruby-full
```
```
$ ruby -v

ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```
```
$ sudo gem install rake
```
```
$ sudo gem install zendesk_apps_tools

Fetching: thor-0.19.4.gem (100%)
Successfully installed thor-0.19.4
Fetching: rubyzip-1.2.1.gem (100%)
Successfully installed rubyzip-1.2.1
Fetching: rack-1.6.10.gem (100%)
Successfully installed rack-1.6.10
Fetching: eventmachine-1.2.7.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing zendesk_apps_tools:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/eventmachine-1.2.7/ext
/usr/bin/ruby2.3 -r ./siteconf20180607-853-124dys5.rb extconf.rb
checking for main() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-cryptolib
        --without-cryptolib
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
        from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
        from /usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
        from /usr/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
        from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from /usr/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `each'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/eventmachine-1.2.7 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.7/gem_make.out
```

**Comment by darlesson** [comment]
I found a fix for this specific error here: https://github.com/fastlane/fastlane/issues/11579

First run:

```
$ sudo apt-get install build-essential dh-autoreconf
```

Run the following again:

```
$ sudo gem install zendesk_apps_tools
```

Then I get a new error:

```
Building native extensions.  This could take a while...
ERROR:  Error installing zendesk_apps_tools:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.6.8.1/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20180607-7886-b9p38l.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.8.1/mkmf.log
```

**Comment by darlesson** [comment]
The following 3 commands resolve the issue:

```
$ sudo apt-get install libpng-dev
$ sudo apt-get install zlib1g-dev
$ sudo gem install zendesk_apps_tools
```

I would recommend to get these steps into the documentation considering you wouldn't need to install them only if you are already had them installed.
