### ISSUE TITLE
zat validation fails for requirementsOnly apps

### ISSUE THREAD

**Issue by willemodendaal** [zendesk/zendesk_apps_tools#254]
Zat validation seems to fail for requirements-only apps. I also raised this issue [on the zendesk forums](https://develop.zendesk.com/hc/en-us/community/posts/360004253147-Reopened-zat-validation-error-for-requirements-only-app-?page=1#community_comment_360002015488).

I get the following error when doing a zat validate:

```
C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:209:in `initialize': Malformed version number string: '' (ArgumentError)
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:200:in `new'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:200:in `new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.10.0/lib/zendesk_apps_support/manifest.rb:105:in `iframe_only?'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/


```

I think ZAT is trying to validate the frameworkVersion, but frameworkVersion is **not** allowed when writing the manifest for a requirements-only app.

This zendesk sample manifest also fails zat validation: https://github.com/zendesk/demo_apps/blob/master/v2/support/requirements_only_sample_app/manifest.json

My environment
- Zat 2.9.8
- Windows 10
- Node 7.10.1
- Ruby 2.3.3p222 (2016-11-21 revision 56859)

**Comment by willemodendaal** [comment]
I could finally get this to work, but only in a **Docker Container**, using Ruby 2.5.1 and only after installing some dependencies not mentioned elsewhere.

I was unable to get this to work in Windows10(Ubuntu bash) or in vanilla Windows 10 with Ruby 2.3. Zat installation fails on those environments. 

If it helps, here is my docker file.

```
FROM ubuntu:bionic-20180724.1 
ENV RUBYOPT -E utf-8
WORKDIR /app

# Install dependencies and ruby 2.5.1
RUN apt-get update \
    && apt-get install -y ruby-full \
    && apt-get install build-essential -y \
    && apt-get install zlib1g-dev -y \
    && apt-get install nodejs -y \
    && ruby -v

# Install zat tools
RUN gem install rake -V
RUN gem install zendesk_apps_tools -V \
    && gem update zendesk_apps_tools -V

COPY . .

# Do zat validate and package (will output on the mount/volume)
RUN zat validate \
    && zat package

ENTRYPOINT ["sh"]

```
