### ISSUE TITLE
Cannot run validate or package on v3.2.0

### ISSUE THREAD

**Issue by andreasonny83** [zendesk/zendesk_apps_tools#313]
When updating `zendesk_apps_tools` to v3.2.0 the follow error message is appearing when running either `zat verify` or `zat package`

Everything working fine when rolling back to `zat 3.1.0` or lower

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin18]
```

```
/Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ipaddress_2-0.13.0/lib/ipaddress_2/ipv4.rb:71:in `initialize': Invalid IP "2.59.287.094" (ArgumentError)
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ipaddress_2-0.13.0/lib/ipaddress_2.rb:55:in `new'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ipaddress_2-0.13.0/lib/ipaddress_2.rb:55:in `parse'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.21.0/lib/zendesk_apps_support/validations/requests.rb:55:in `blocked_ip_type'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.21.0/lib/zendesk_apps_support/validations/requests.rb:41:in `block in blocked_ips_validation'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.21.0/lib/zendesk_apps_support/validations/requests.rb:40:in `each'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.21.0/lib/zendesk_apps_support/validations/requests.rb:40:in `each_with_object'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.21.0/lib/zendesk_apps_support/validations/requests.rb:40:in `blocked_ips_validation'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.21.0/lib/zendesk_apps_support/validations/requests.rb:30:in `block in call'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.21.0/lib/zendesk_apps_support/validations/requests.rb:16:in `each'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.21.0/lib/zendesk_apps_support/validations/requests.rb:16:in `call'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_support-4.21.0/lib/zendesk_apps_support/package.rb:40:in `validate'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-3.2.0/lib/zendesk_apps_tools/command.rb:92:in `validate'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-3.2.0/lib/zendesk_apps_tools/command.rb:121:in `package'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /Users/myuser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-3.2.0/bin/zat:13:in `<top (required)>'
        from /Users/myuser/.rbenv/versions/2.3.0/bin/zat:23:in `load'
        from /Users/myuser/.rbenv/versions/2.3.0/bin/zat:23:in `<main>'
```

**Comment by romankosiuh** [comment]
The same issue:
```bash
$ zat package
/Library/Ruby/Gems/2.3.0/gems/ipaddress_2-0.13.0/lib/ipaddress_2/ipv4.rb:71:in `initialize': Invalid IP "128.664.299.002" (ArgumentError)
        from /Library/Ruby/Gems/2.3.0/gems/ipaddress_2-0.13.0/lib/ipaddress_2.rb:55:in `new'
        from /Library/Ruby/Gems/2.3.0/gems/ipaddress_2-0.13.0/lib/ipaddress_2.rb:55:in `parse'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_support-4.21.1/lib/zendesk_apps_support/validations/requests.rb:55:in `blocked_ip_type'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_support-4.21.1/lib/zendesk_apps_support/validations/requests.rb:41:in `block in blocked_ips_validation'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_support-4.21.1/lib/zendesk_apps_support/validations/requests.rb:40:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_support-4.21.1/lib/zendesk_apps_support/validations/requests.rb:40:in `each_with_object'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_support-4.21.1/lib/zendesk_apps_support/validations/requests.rb:40:in `blocked_ips_validation'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_support-4.21.1/lib/zendesk_apps_support/validations/requests.rb:30:in `block in call'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_support-4.21.1/lib/zendesk_apps_support/validations/requests.rb:16:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_support-4.21.1/lib/zendesk_apps_support/validations/requests.rb:16:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_support-4.21.1/lib/zendesk_apps_support/package.rb:40:in `validate'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_tools-3.2.1/lib/zendesk_apps_tools/command.rb:92:in `validate'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_tools-3.2.1/lib/zendesk_apps_tools/command.rb:121:in `package'
        from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /Library/Ruby/Gems/2.3.0/gems/zendesk_apps_tools-3.2.1/bin/zat:13:in `<top (required)>'
        from /usr/local/bin/zat:22:in `load'
        from /usr/local/bin/zat:22:in `<main>'
```
```bash
$ ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

```
