### ISSUE TITLE
`block in invalid_location_error': undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by thomasfaller** [zendesk/zendesk_apps_tools#350]
Whenever I run a zat command (except zat server which seems to work ok) I get the following :

```bash
Traceback (most recent call last):
        14: from /usr/local/bin/zat:23:in `<main>'
        13: from /usr/local/bin/zat:23:in `load'
        12: from /var/lib/gems/2.7.0/gems/zendesk_apps_tools-3.8.1/bin/zat:13:in `<top (required)>'
        11: from /var/lib/gems/2.7.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        10: from /var/lib/gems/2.7.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
         9: from /var/lib/gems/2.7.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
         8: from /var/lib/gems/2.7.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
         7: from /var/lib/gems/2.7.0/gems/zendesk_apps_tools-3.8.1/lib/zendesk_apps_tools/command.rb:92:in `validate'
         6: from /var/lib/gems/2.7.0/gems/zendesk_apps_support-4.29.5/lib/zendesk_apps_support/package.rb:36:in `validate'
         5: from /var/lib/gems/2.7.0/gems/zendesk_apps_support-4.29.5/lib/zendesk_apps_support/validations/manifest.rb:25:in `call'
         4: from /var/lib/gems/2.7.0/gems/zendesk_apps_support-4.29.5/lib/zendesk_apps_support/validations/manifest.rb:47:in `collate_manifest_errors'
         3: from /var/lib/gems/2.7.0/gems/zendesk_apps_support-4.29.5/lib/zendesk_apps_support/validations/manifest.rb:60:in `validate_location'
         2: from /var/lib/gems/2.7.0/gems/zendesk_apps_support-4.29.5/lib/zendesk_apps_support/validations/manifest.rb:268:in `invalid_location_error'
         1: from /var/lib/gems/2.7.0/gems/zendesk_apps_support-4.29.5/lib/zendesk_apps_support/validations/manifest.rb:268:in `each'
/var/lib/gems/2.7.0/gems/zendesk_apps_support-4.29.5/lib/zendesk_apps_support/validations/manifest.rb:272:in `block in invalid_location_error': undefined method `name' for nil:NilClass (NoMethodError)
```

Not really seeing what that refers to. Any help would be greatly appreciated.

**Comment by nishajgd** [comment]
I am facing the same  issue now. 
@thomasfaller If you found a solution it would help me too. Thank you so much!

**Comment by 3v01ut10n** [comment]
**zat server** does not cause problems.
But **zat validate and** **zat package** not working.

```
Traceback (most recent call last):
	14: from /home/denis/.rbenv/versions/2.6.3/bin/zat:23:in `<main>'
	13: from /home/denis/.rbenv/versions/2.6.3/bin/zat:23:in `load'
	12: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zendesk_apps_tools-3.8.4/bin/zat:13:in `<top (required)>'
	11: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	10: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	 9: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	 8: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	 7: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zendesk_apps_tools-3.8.4/lib/zendesk_apps_tools/command.rb:92:in `validate'
	 6: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zendesk_apps_support-4.29.10/lib/zendesk_apps_support/package.rb:36:in `validate'
	 5: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zendesk_apps_support-4.29.10/lib/zendesk_apps_support/validations/manifest.rb:25:in `call'
	 4: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zendesk_apps_support-4.29.10/lib/zendesk_apps_support/validations/manifest.rb:47:in `collate_manifest_errors'
	 3: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zendesk_apps_support-4.29.10/lib/zendesk_apps_support/validations/manifest.rb:60:in `validate_location'
	 2: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zendesk_apps_support-4.29.10/lib/zendesk_apps_support/validations/manifest.rb:268:in `invalid_location_error'
	 1: from /home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zendesk_apps_support-4.29.10/lib/zendesk_apps_support/validations/manifest.rb:268:in `each'
/home/denis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/zendesk_apps_support-4.29.10/lib/zendesk_apps_support/validations/manifest.rb:272:in `block in invalid_location_error': undefined method `name' for nil:NilClass (NoMethodError)
```

**Comment by jonaniano** [comment]
Although this error is not very descriptive, it actually does indicate a problem with the manifest file. 

I was getting this error for a while and I manually created the package and uploaded it, and I received the same validation error from the Zendesk app upload screen. 

I was using the manifest that was created from the "zat new" command, so, it shouldn't have been wrong (I suspect it may be the '"flexible": true' line in the support app, but, who knows.

I tossed the default manifest file and I created a new manifest filed from the example here and it worked:

https://github.com/zendesk/demo_apps/blob/master/v2/support/basic_ticket_sample_app/manifest.json

**Comment by 3v01ut10n** [comment]
> I tossed the default manifest file and I created a new manifest filed from the example here and it worked:
> 
> https://github.com/zendesk/demo_apps/blob/master/v2/support/basic_ticket_sample_app/manifest.json

It worked for me too, thanks!

**Comment by BenHND** [comment]
Same issue when adding "flexible": true to the manifest file.
