### ISSUE TITLE
JSON parsing error when attempting to execute most commands

### ISSUE THREAD

**Issue by Marco-Pagani** [zendesk/zendesk_apps_tools#359]
Hello all, I've installed ZAT to my system (macOS Catalina) and I cannot execute any commands, as I get the same exception each time:
```
❯ zat update
/Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/options.rb:153: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/options.rb:153: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/options.rb:153: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/options.rb:153: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/options.rb:153: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
Traceback (most recent call last):
	11: from /Users/marco.pagani/.rbenv/versions/2.7.0/bin/zat:23:in `<main>'
	10: from /Users/marco.pagani/.rbenv/versions/2.7.0/bin/zat:23:in `load'
	 9: from /Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zendesk_apps_tools-3.8.1/bin/zat:13:in `<top (required)>'
	 8: from /Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	 7: from /Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	 6: from /Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	 5: from /Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	 4: from /Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zendesk_apps_tools-3.8.1/lib/zendesk_apps_tools/command.rb:216:in `update'
	 3: from /Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zendesk_apps_tools-3.8.1/lib/zendesk_apps_tools/cache.rb:23:in `fetch'
	 2: from /Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zendesk_apps_tools-3.8.1/lib/zendesk_apps_tools/cache.rb:33:in `local_cache'
	 1: from /Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
/Users/marco.pagani/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse': 784: unexpected token at '' (JSON::ParserError)
```

This occurs with any of the zat commands and I've had no luck zeroing in on the problem. I fully cleaned my ruby environment and reinstalled it (`rbenv` running 2.7.0) I also updated the `json` gem but I'm stuck as to where I can go from here. Any help is appreciated

**Comment by Marco-Pagani** [comment]
After much pain and suffering I've found the issue. This error occurs if your root directory has a `.zat` file that's empty. It seems that I cleared the contents of that file at some point in my setup process. You can simply delete it and run `zat validate` to generate a new one and carry on.
