### ISSUE TITLE
Theme Preview - Upload Failed: Execution Expired

### ISSUE THREAD

**Issue by ohitsdylan** [zendesk/zendesk_apps_tools#369]
Occasionally (occurs from half an hour to a few hours of the ZAT server being started) ZAT will throw this error message at me (below).

After this error occurs, the server does not load any new file changes. Stopping the server and restarting resolves it for some period of time. Just noting here that the server does not crash, but hangs.

Has anyone else experienced this?
A fix would save me a lot of time wondering why my HTML/CSS changes aren't doing anything. 🙃

I am on ZAT version 3.8.2

```
Uploading  Failed: execution expired
#<Thread:0x00007ffff4fb62a0 /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:341 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        21: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:341:in `block in _start_wait_thread'
        20: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:252:in `_wait_for_changes'
        19: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:252:in `loop'
        18: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:269:in `block in _wait_for_changes'
        17: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:305:in `_process_changes'
        16: from /home/dylan/gems/gems/zendesk_apps_tools-3.8.2/lib/zendesk_apps_tools/theme.rb:74:in `block in start_listener'
        15: from /home/dylan/gems/gems/zendesk_apps_tools-3.8.2/lib/zendesk_apps_tools/theme.rb:34:in `full_upload'
        14: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `put'
        13: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        12: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        11: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
        10: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
         9: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
         8: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
         7: from /usr/lib/ruby/2.7.0/net/http.rb:1483:in `request'
         6: from /usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
         5: from /usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         4: from /usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
         3: from /var/lib/gems/2.7.0/gems/timeout-0.1.1/lib/timeout.rb:107:in `timeout'
         2: from /usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
         1: from /usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize': execution expired (Net::OpenTimeout)
        21: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:341:in `block in _start_wait_thread'
        20: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:252:in `_wait_for_changes'
        19: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:252:in `loop'
        18: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:269:in `block in _wait_for_changes'
        17: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:305:in `_process_changes'
        16: from /home/dylan/gems/gems/zendesk_apps_tools-3.8.2/lib/zendesk_apps_tools/theme.rb:74:in `block in start_listener'
        15: from /home/dylan/gems/gems/zendesk_apps_tools-3.8.2/lib/zendesk_apps_tools/theme.rb:34:in `full_upload'
        14: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `put'
        13: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        12: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        11: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
        10: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
         9: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
         8: from /var/lib/gems/2.7.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
         7: from /usr/lib/ruby/2.7.0/net/http.rb:1483:in `request'
         6: from /usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
         5: from /usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         4: from /usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
         3: from /var/lib/gems/2.7.0/gems/timeout-0.1.1/lib/timeout.rb:107:in `timeout'
         2: from /usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
         1: from /usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize': execution expired (Faraday::ConnectionFailed)
        7: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:341:in `block in _start_wait_thread'
        6: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:252:in `_wait_for_changes'
        5: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:252:in `loop'
        4: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:269:in `block in _wait_for_changes'
        3: from /var/lib/gems/2.7.0/gems/listen-2.10.1/lib/listen/listener.rb:305:in `_process_changes'
        2: from /home/dylan/gems/gems/zendesk_apps_tools-3.8.2/lib/zendesk_apps_tools/theme.rb:74:in `block in start_listener'
        1: from /home/dylan/gems/gems/zendesk_apps_tools-3.8.2/lib/zendesk_apps_tools/theme.rb:27:in `full_upload'
/home/dylan/gems/gems/zendesk_apps_tools-3.8.2/lib/zendesk_apps_tools/theme.rb:45:in `rescue in full_upload': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by ohitsdylan** [comment]
Given all of the `faraday` references in that log, I'm going to try running ZAT with #355 to see if anything changes. 🤷‍♀️

**Comment by ohitsdylan** [comment]
I've been sitting on the theme preview with the Faraday updates and it seems to have resolved the issue. I've been making a lot of local changes and have had the server running for a few hours and nothing has failed.

I guess if anyone else is experiencing this, try bumping up the Faraday gem version. Hooray~ ✨

**Comment by ohitsdylan** [comment]
Haven't seen this message in a while. 🤷‍♀️
